### ISSUE TITLE
Crash when Chisel is not installed

### ISSUE THREAD

**Issue by sblectric** [iamomicron/UsefulDNS#2]
The following crash occurs when UsefulDNS attempts Chisel integration without Chisel. [crash-2016-02-13_23.38.33-client.txt](https://github.com/iamomicron/UsefulDNS/files/129526/crash-2016-02-13_23.38.33-client.txt)

**Comment by iamomicron** [comment]
Huh. That's interesting. Seemed to work for me. Can you confirm that it no longer crashes if chisel is installed?

Will fix it tomorrow when I get back, in any case.

**Comment by sblectric** [comment]
The crash only started happening after I removed Chisel from my pack.

**Comment by sblectric** [comment]
Rolled back to 2.0.0 and it's working, as well

**Comment by iamomicron** [comment]
Alright, I'll try to fix it tomorrow. Have to get back to uni, will be late afternoon.

**Comment by sblectric** [comment]
Thanks, cool mod btw

**Comment by iamomicron** [comment]
Fixed in **2.0.2**
