### ISSUE TITLE
1.8.9-Crash called NoClassDefFoundError

### ISSUE THREAD

**Issue by WenXin20** [iamomicron/UsefulDNS#3]
DNS 2.1.1, Forge 1741, 
Crash Log: 
http://pastebin.com/igbhZQJf

**Comment by iamomicron** [comment]
Is Chisel installed?

**Comment by iamomicron** [comment]
Nevermind, found the issue! Fixed in **2.1.2**.

**Comment by WenXin20** [comment]
K, thanks
