### ISSUE TITLE
Server crash: java.lang.NoClassDefFoundError: slimeknights/tconstruct/library/client/MaterialRenderInfo

### ISSUE THREAD

**Issue by sblectric** [iamomicron/UsefulDNS#4]
This crash occurs when starting the server. http://pastebin.com/LEbQq186
The server is looking for a clientside Tinker's Construct class for some reason.

Tinker's version 1.8.9-2.1.0
UsefulDNS version 2.2.1

**Comment by iamomicron** [comment]
Whoops, my bad. Will release 2.2.2 soon.
